---
- name: install key (apt)
  become: yes
  apt_key:
    url: 'https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg'
    keyring: '/etc/apt/trusted.gpg.d/spotify.gpg'
    state: present

- name: install spotify-client repo (apt)
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/spotify.gpg ] http://repository.spotify.com stable non-free'
    filename: spotify-client
    state: present

- name: install spotify-client (apt)
  become: yes
  apt:
    name: "spotify-client"
    state: present
